version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test:junit

      - store_artifacts:
          path: ./output

      - store_test_results:
          path: ./output


workflows:
  version: 2.1
  build:
    jobs:
      - test