version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - run: sudo apt-add-repository ppa:qameta/allure
      - run: sudo apt-get update
      - run: sudo apt-get install allure

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      - store_artifacts:
          path: ./output

      # restore before allure report for save history of allure report
      - restore_cache:
          keys:
            - v1-allure-report
      
      - run: npm run report:allure

      - store_artifacts:
          path: ./allure-report

      - save_cache:
          paths:
            - allure-report
          key: v1-allure-report
